In [2]:
import pandas as pd
import numpy as np

In [3]:
# Read the same raw file EDA used
df = pd.read_csv("../data/processed/laps_2023.csv")

print("Shape of the dataset:", df.shape)

Shape of the dataset: (11255, 33)

In [6]:
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,RaceName,Year
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.414000,...,0 days 01:02:36.652000,NaN,12,1.0,NaN,NaN,False,False,Bahrain,2023
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,...,0 days 01:04:15.902000,NaN,12,1.0,NaN,NaN,False,True,Bahrain,2023
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,...,0 days 01:05:53.876000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,...,0 days 01:07:31.882000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,...,0 days 01:09:09.858000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023

In [8]:
# Drop useless columns (100% missing)
df.drop(columns = ["LapStartDate", "Deleted", "DeletedReason"], inplace = True)
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.414000,...,4.0,False,Red Bull Racing,0 days 01:02:36.652000,12,1.0,False,False,Bahrain,2023
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,...,5.0,False,Red Bull Racing,0 days 01:04:15.902000,12,1.0,False,True,Bahrain,2023
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,...,6.0,False,Red Bull Racing,0 days 01:05:53.876000,1,1.0,False,True,Bahrain,2023
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,...,7.0,False,Red Bull Racing,0 days 01:07:31.882000,1,1.0,False,True,Bahrain,2023
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,...,8.0,False,Red Bull Racing,0 days 01:09:09.858000,1,1.0,False,True,Bahrain,2023

#### Features with 100% missing values were dropped cause it carries zero information

---------------------------------------------------------------

In [12]:
# Time related columns 
time_col = [feature for feature in df.columns if ("Time" in feature) or ("Date" in feature)]
print(time_col)

df[time_col].head(10)

['Time', 'LapTime', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'LapStartTime']

,Time,LapTime,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,LapStartTime
0,0 days 01:04:15.902000,0 days 00:01:39.019000,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,0 days 01:02:36.652000
1,0 days 01:05:53.876000,0 days 00:01:37.974000,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,0 days 01:04:15.902000
2,0 days 01:07:31.882000,0 days 00:01:38.006000,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,0 days 01:05:53.876000
3,0 days 01:09:09.858000,0 days 00:01:37.976000,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,0 days 01:07:31.882000
4,0 days 01:10:47.893000,0 days 00:01:38.035000,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,0 days 01:09:09.858000
5,0 days 01:12:25.879000,0 days 00:01:37.986000,NaN,NaN,0 days 00:00:31.341000,0 days 00:00:42.632000,0 days 00:00:24.013000,0 days 01:11:19.293000,0 days 01:12:01.925000,0 days 01:12:25.938000,0 days 01:10:47.893000
6,0 days 01:14:03.900000,0 days 00:01:38.021000,NaN,NaN,0 days 00:00:31.290000,0 days 00:00:42.763000,0 days 00:00:23.968000,0 days 01:12:57.228000,0 days 01:13:39.991000,0 days 01:14:03.959000,0 days 01:12:25.879000
7,0 days 01:15:42.054000,0 days 00:01:38.154000,NaN,NaN,0 days 00:00:31.291000,0 days 00:00:42.833000,0 days 00:00:24.030000,0 days 01:14:35.250000,0 days 01:15:18.083000,0 days 01:15:42.113000,0 days 01:14:03.900000
8,0 days 01:17:20.332000,0 days 00:01:38.278000,NaN,NaN,0 days 00:00:31.336000,0 days 00:00:42.823000,0 days 00:00:24.119000,0 days 01:16:13.449000,0 days 01:16:56.272000,0 days 01:17:20.391000,0 days 01:15:42.054000
9,0 days 01:18:58.701000,0 days 00:01:38.369000,NaN,NaN,0 days 00:00:31.361000,0 days 00:00:42.884000,0 days 00:00:24.124000,0 days 01:17:51.752000,0 days 01:18:34.636000,0 days 01:18:58.760000,0 days 01:17:20.332000

In [14]:
# Convert timedelta ----> seconds

# Strip column name incase of hidden space
df.columns = df.columns.str.strip()

for col in time_col:
    df[col]= pd.to_timedelta(df[col], errors = "coerce").dt.total_seconds()

df[time_col].head()

,Time,LapTime,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,LapStartTime
0,3855.902,99.019,NaN,NaN,NaN,42.414,23.842,NaN,3832.119,3856.010,3756.652
1,3953.876,97.974,NaN,NaN,31.342,42.504,24.128,3887.303,3929.807,3953.935,3855.902
2,4051.882,98.006,NaN,NaN,31.388,42.469,24.149,3985.323,4027.792,4051.941,3953.876
3,4149.858,97.976,NaN,NaN,31.271,42.642,24.063,4083.212,4125.854,4149.917,4051.882
4,4247.893,98.035,NaN,NaN,31.244,42.724,24.067,4181.161,4223.885,4247.952,4149.858

In [17]:
print(df[time_col].dtypes)

Time                  float64
LapTime               float64
PitOutTime            float64
PitInTime             float64
Sector1Time           float64
Sector2Time           float64
Sector3Time           float64
Sector1SessionTime    float64
Sector2SessionTime    float64
Sector3SessionTime    float64
LapStartTime          float64
dtype: object

--------

In [ ]:
# Fix categorical vs numerical cols